name: Github-Action-Test

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          # Yarn 캐시 활성화
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Environment Variables File
        run: |
          echo "VITE_TEST=$VITE_TEST" >> .env.local
          echo "VITE_TEST is $VITE_TEST"
        env:
          VITE_TEST: ${{ secrets.VITE_TEST }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build

      # # ubuntu 서버에 접속하여 빌드 파일을 전송하고 배포된 파일을 교체
      # - name: Execute Remote SSH & Deploy
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.REMOTE_SSH_HOST }}
      #     username: ${{ secrets.REMOTE_SSH_USERNAME }}
      #     key: ${{ secrets.REMOTE_SSH_KEY }}
      #     source: ./out
      #     target: /home/${{ secrets.REMOTE_SSH_USERNAME }}/test

  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://ca.slack-edge.com/T07QZJPNXRD-U07RE5DGSR0-38d3c1f0c1ee-512
          SLACK_MESSAGE: "Post Content :rocket:"
          SLACK_TITLE: Post Title
          SLACK_USERNAME: UuUUUUUUSERNAME
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
