name: Github-Action-Test

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Environment Variables File
        run: |
          echo "VITE_TEST=$VITE_TEST" >> .env.local
          echo "VITE_TEST is $VITE_TEST"
        env:
          VITE_ENV_TEST: ${{ secrets.VITE_ENV_TEST }}
      - name: Install Dependencies
        run: yarn
      - name: Check Lint
        run: yarn lint
      - name: Delete ./out & Build
        run: |
          rm -rf ./out
          yarn build
      - name: Connect with Remote Server
        run: echo "SSH - Connect with remote server"
      - name: Copy files to Remote Server
        run: echo "SCP - Copy files to remote server"
